#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DEF_PATH = ROOT / "abi" / "syscalls.def"
KERNEL_NR_PATH = ROOT / "kernel" / "src" / "syscall" / "nr.rs"
KERNEL_DISPATCH_PATH = ROOT / "kernel" / "src" / "syscall" / "dispatch.rs"
USER_HEADER_PATH = ROOT / "user" / "libcshim" / "sysnr.h"


@dataclass(frozen=True)
class Syscall:
    name: str
    number: int
    user_name: str
    handler: str


def parse_definitions() -> list[Syscall]:
    entries: list[Syscall] = []
    for lineno, raw in enumerate(DEF_PATH.read_text().splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        parts = [part.strip() for part in line.split("|", 3)]
        if len(parts) != 4:
            raise SystemExit(f"{DEF_PATH}:{lineno}: expected 4 fields, got {len(parts)}")

        name, number, user_name, handler = parts
        entries.append(Syscall(name=name, number=int(number, 0), user_name=user_name, handler=handler))

    seen_names: set[str] = set()
    seen_numbers: set[int] = set()
    for entry in entries:
        if entry.name in seen_names:
            raise SystemExit(f"duplicate syscall name: {entry.name}")
        if entry.number in seen_numbers:
            raise SystemExit(f"duplicate syscall number: {entry.number}")
        seen_names.add(entry.name)
        seen_numbers.add(entry.number)

    return sorted(entries, key=lambda entry: entry.number)


def render_nr(entries: list[Syscall]) -> str:
    consts = "\n".join(f"pub const {entry.name}: u64 = {entry.number};" for entry in entries)
    all_entries = ",\n".join(
        f'    SyscallMeta {{ number: {entry.name}, name: "{entry.user_name}" }}' for entry in entries
    )
    names = "\n".join(
        f'        {entry.name} => Some("{entry.user_name}"),' for entry in entries
    )
    return f"""// @generated by tools/generate_syscalls.py from abi/syscalls.def
#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SyscallMeta {{
    pub number: u64,
    pub name: &'static str,
}}

{consts}

#[allow(dead_code)]
pub const ALL: &[SyscallMeta] = &[
{all_entries}
];

#[allow(dead_code)]
pub fn name(number: u64) -> Option<&'static str> {{
    match number {{
{names}
        _ => None,
    }}
}}
"""


def render_dispatch(entries: list[Syscall]) -> str:
    arms = "\n".join(
        f"        nr::{entry.name} => {entry.handler}," for entry in entries
    )
    return f"""// @generated by tools/generate_syscalls.py from abi/syscalls.def
use super::{{io, mm, net, nr, process, sys, time, vfs}};

pub unsafe fn route(num: u64, arg1: u64, arg2: u64, arg3: u64, arg4: u64, frame: u64) -> u64 {{
    match num {{
{arms}
        _ => {{
            crate::dbg_log!(
                "SYSCALL",
                "unhandled syscall {{}} ({{:?}})",
                num,
                nr::name(num)
            );
            crate::syscall::result::errno(crate::syscall::result::SysError::NoSys)
        }}
    }}
}}
"""


def render_header(entries: list[Syscall]) -> str:
    defines = "\n".join(
        f"#define COREOS_SYS_{entry.name} {entry.number}" for entry in entries
    )
    return f"""/* @generated by tools/generate_syscalls.py from abi/syscalls.def */
#pragma once

{defines}
"""


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


def main() -> None:
    entries = parse_definitions()
    write_if_changed(KERNEL_NR_PATH, render_nr(entries))
    write_if_changed(KERNEL_DISPATCH_PATH, render_dispatch(entries))
    write_if_changed(USER_HEADER_PATH, render_header(entries))


if __name__ == "__main__":
    main()
