// @generated by tools/generate_syscalls.py from abi/syscalls.def
#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SyscallMeta {
    pub number: u64,
    pub name: &'static str,
}

pub const READ: u64 = 0;
pub const WRITE: u64 = 1;
pub const OPEN: u64 = 3;
pub const CLOSE: u64 = 4;
pub const FSIZE: u64 = 5;
pub const LS: u64 = 6;
pub const TOUCH: u64 = 7;
pub const RM: u64 = 8;
pub const WRITE_FILE: u64 = 9;
pub const PUSH_FILE: u64 = 10;
pub const BRK: u64 = 12;
pub const RT_SIGACTION: u64 = 13;
pub const RT_SIGPROCMASK: u64 = 14;
pub const IOCTL: u64 = 16;
pub const READV: u64 = 19;
pub const WRITEV: u64 = 20;
pub const UPTIME_SECONDS: u64 = 21;
pub const PIPE: u64 = 22;
pub const REBOOT: u64 = 23;
pub const PANIC: u64 = 24;
pub const BOOTTIME: u64 = 25;
pub const CLEAR_TERMINAL: u64 = 26;
pub const SLEEP_TICKS: u64 = 27;
pub const SET_FONT_SCALE: u64 = 28;
pub const FSTAT: u64 = 29;
pub const LSEEK: u64 = 30;
pub const MMAP: u64 = 31;
pub const MPROTECT: u64 = 32;
pub const MUNMAP: u64 = 33;
pub const DUP: u64 = 34;
pub const NANOSLEEP: u64 = 35;
pub const FREE_BYTES: u64 = 36;
pub const TICKS: u64 = 37;
pub const GETPID: u64 = 39;
pub const SOCKET: u64 = 41;
pub const CONNECT: u64 = 42;
pub const ACCEPT: u64 = 43;
pub const SENDTO: u64 = 44;
pub const RECVFROM: u64 = 45;
pub const SHUTDOWN: u64 = 48;
pub const BIND: u64 = 49;
pub const LISTEN: u64 = 50;
pub const GETSOCKNAME: u64 = 51;
pub const GETPEERNAME: u64 = 52;
pub const SOCKETPAIR: u64 = 53;
pub const SETSOCKOPT: u64 = 54;
pub const GETSOCKOPT: u64 = 55;
pub const EXEC: u64 = 57;
pub const FORK: u64 = 58;
pub const EXIT: u64 = 60;
pub const WAITPID: u64 = 61;
pub const KILL: u64 = 62;
pub const UNAME: u64 = 63;
pub const FCNTL: u64 = 72;
pub const GETCWD: u64 = 79;
pub const CHDIR: u64 = 80;
pub const UMASK: u64 = 95;
pub const GETRLIMIT: u64 = 97;
pub const SYSINFO: u64 = 99;
pub const GETUID: u64 = 102;
pub const GETGID: u64 = 104;
pub const SETUID: u64 = 105;
pub const SETGID: u64 = 106;
pub const GETEUID: u64 = 107;
pub const GETEGID: u64 = 108;
pub const SETPGID: u64 = 109;
pub const GETPPID: u64 = 110;
pub const GETPGRP: u64 = 111;
pub const GETRESUID: u64 = 118;
pub const GETRESGID: u64 = 120;
pub const GETPGID: u64 = 121;
pub const GETSID: u64 = 124;
pub const SIGALTSTACK: u64 = 131;
pub const SETRLIMIT: u64 = 160;
pub const GETTID: u64 = 186;
pub const SET_TID_ADDRESS: u64 = 218;
pub const CLOCK_GETTIME: u64 = 228;
pub const OPENAT: u64 = 257;
pub const FSTATAT: u64 = 262;
pub const FACCESSAT: u64 = 269;
pub const ACCEPT4: u64 = 288;
pub const DUP3: u64 = 292;
pub const PIPE2: u64 = 293;
pub const PRLIMIT64: u64 = 302;

#[allow(dead_code)]
pub const ALL: &[SyscallMeta] = &[
    SyscallMeta { number: READ, name: "read" },
    SyscallMeta { number: WRITE, name: "write" },
    SyscallMeta { number: OPEN, name: "open" },
    SyscallMeta { number: CLOSE, name: "close" },
    SyscallMeta { number: FSIZE, name: "fsize" },
    SyscallMeta { number: LS, name: "ls" },
    SyscallMeta { number: TOUCH, name: "touch" },
    SyscallMeta { number: RM, name: "rm" },
    SyscallMeta { number: WRITE_FILE, name: "write_file" },
    SyscallMeta { number: PUSH_FILE, name: "push_file" },
    SyscallMeta { number: BRK, name: "brk" },
    SyscallMeta { number: RT_SIGACTION, name: "rt_sigaction" },
    SyscallMeta { number: RT_SIGPROCMASK, name: "rt_sigprocmask" },
    SyscallMeta { number: IOCTL, name: "ioctl" },
    SyscallMeta { number: READV, name: "readv" },
    SyscallMeta { number: WRITEV, name: "writev" },
    SyscallMeta { number: UPTIME_SECONDS, name: "uptime_seconds" },
    SyscallMeta { number: PIPE, name: "pipe" },
    SyscallMeta { number: REBOOT, name: "reboot" },
    SyscallMeta { number: PANIC, name: "panic" },
    SyscallMeta { number: BOOTTIME, name: "boottime" },
    SyscallMeta { number: CLEAR_TERMINAL, name: "clear_terminal" },
    SyscallMeta { number: SLEEP_TICKS, name: "sleep_ticks" },
    SyscallMeta { number: SET_FONT_SCALE, name: "set_font_scale" },
    SyscallMeta { number: FSTAT, name: "fstat" },
    SyscallMeta { number: LSEEK, name: "lseek" },
    SyscallMeta { number: MMAP, name: "mmap" },
    SyscallMeta { number: MPROTECT, name: "mprotect" },
    SyscallMeta { number: MUNMAP, name: "munmap" },
    SyscallMeta { number: DUP, name: "dup" },
    SyscallMeta { number: NANOSLEEP, name: "nanosleep" },
    SyscallMeta { number: FREE_BYTES, name: "free_bytes" },
    SyscallMeta { number: TICKS, name: "ticks" },
    SyscallMeta { number: GETPID, name: "getpid" },
    SyscallMeta { number: SOCKET, name: "socket" },
    SyscallMeta { number: CONNECT, name: "connect" },
    SyscallMeta { number: ACCEPT, name: "accept" },
    SyscallMeta { number: SENDTO, name: "sendto" },
    SyscallMeta { number: RECVFROM, name: "recvfrom" },
    SyscallMeta { number: SHUTDOWN, name: "shutdown" },
    SyscallMeta { number: BIND, name: "bind" },
    SyscallMeta { number: LISTEN, name: "listen" },
    SyscallMeta { number: GETSOCKNAME, name: "getsockname" },
    SyscallMeta { number: GETPEERNAME, name: "getpeername" },
    SyscallMeta { number: SOCKETPAIR, name: "socketpair" },
    SyscallMeta { number: SETSOCKOPT, name: "setsockopt" },
    SyscallMeta { number: GETSOCKOPT, name: "getsockopt" },
    SyscallMeta { number: EXEC, name: "exec" },
    SyscallMeta { number: FORK, name: "fork" },
    SyscallMeta { number: EXIT, name: "exit" },
    SyscallMeta { number: WAITPID, name: "waitpid" },
    SyscallMeta { number: KILL, name: "kill" },
    SyscallMeta { number: UNAME, name: "uname" },
    SyscallMeta { number: FCNTL, name: "fcntl" },
    SyscallMeta { number: GETCWD, name: "getcwd" },
    SyscallMeta { number: CHDIR, name: "chdir" },
    SyscallMeta { number: UMASK, name: "umask" },
    SyscallMeta { number: GETRLIMIT, name: "getrlimit" },
    SyscallMeta { number: SYSINFO, name: "sysinfo" },
    SyscallMeta { number: GETUID, name: "getuid" },
    SyscallMeta { number: GETGID, name: "getgid" },
    SyscallMeta { number: SETUID, name: "setuid" },
    SyscallMeta { number: SETGID, name: "setgid" },
    SyscallMeta { number: GETEUID, name: "geteuid" },
    SyscallMeta { number: GETEGID, name: "getegid" },
    SyscallMeta { number: SETPGID, name: "setpgid" },
    SyscallMeta { number: GETPPID, name: "getppid" },
    SyscallMeta { number: GETPGRP, name: "getpgrp" },
    SyscallMeta { number: GETRESUID, name: "getresuid" },
    SyscallMeta { number: GETRESGID, name: "getresgid" },
    SyscallMeta { number: GETPGID, name: "getpgid" },
    SyscallMeta { number: GETSID, name: "getsid" },
    SyscallMeta { number: SIGALTSTACK, name: "sigaltstack" },
    SyscallMeta { number: SETRLIMIT, name: "setrlimit" },
    SyscallMeta { number: GETTID, name: "gettid" },
    SyscallMeta { number: SET_TID_ADDRESS, name: "set_tid_address" },
    SyscallMeta { number: CLOCK_GETTIME, name: "clock_gettime" },
    SyscallMeta { number: OPENAT, name: "openat" },
    SyscallMeta { number: FSTATAT, name: "fstatat" },
    SyscallMeta { number: FACCESSAT, name: "faccessat" },
    SyscallMeta { number: ACCEPT4, name: "accept4" },
    SyscallMeta { number: DUP3, name: "dup3" },
    SyscallMeta { number: PIPE2, name: "pipe2" },
    SyscallMeta { number: PRLIMIT64, name: "prlimit64" }
];

#[allow(dead_code)]
pub fn name(number: u64) -> Option<&'static str> {
    match number {
        READ => Some("read"),
        WRITE => Some("write"),
        OPEN => Some("open"),
        CLOSE => Some("close"),
        FSIZE => Some("fsize"),
        LS => Some("ls"),
        TOUCH => Some("touch"),
        RM => Some("rm"),
        WRITE_FILE => Some("write_file"),
        PUSH_FILE => Some("push_file"),
        BRK => Some("brk"),
        RT_SIGACTION => Some("rt_sigaction"),
        RT_SIGPROCMASK => Some("rt_sigprocmask"),
        IOCTL => Some("ioctl"),
        READV => Some("readv"),
        WRITEV => Some("writev"),
        UPTIME_SECONDS => Some("uptime_seconds"),
        PIPE => Some("pipe"),
        REBOOT => Some("reboot"),
        PANIC => Some("panic"),
        BOOTTIME => Some("boottime"),
        CLEAR_TERMINAL => Some("clear_terminal"),
        SLEEP_TICKS => Some("sleep_ticks"),
        SET_FONT_SCALE => Some("set_font_scale"),
        FSTAT => Some("fstat"),
        LSEEK => Some("lseek"),
        MMAP => Some("mmap"),
        MPROTECT => Some("mprotect"),
        MUNMAP => Some("munmap"),
        DUP => Some("dup"),
        NANOSLEEP => Some("nanosleep"),
        FREE_BYTES => Some("free_bytes"),
        TICKS => Some("ticks"),
        GETPID => Some("getpid"),
        SOCKET => Some("socket"),
        CONNECT => Some("connect"),
        ACCEPT => Some("accept"),
        SENDTO => Some("sendto"),
        RECVFROM => Some("recvfrom"),
        SHUTDOWN => Some("shutdown"),
        BIND => Some("bind"),
        LISTEN => Some("listen"),
        GETSOCKNAME => Some("getsockname"),
        GETPEERNAME => Some("getpeername"),
        SOCKETPAIR => Some("socketpair"),
        SETSOCKOPT => Some("setsockopt"),
        GETSOCKOPT => Some("getsockopt"),
        EXEC => Some("exec"),
        FORK => Some("fork"),
        EXIT => Some("exit"),
        WAITPID => Some("waitpid"),
        KILL => Some("kill"),
        UNAME => Some("uname"),
        FCNTL => Some("fcntl"),
        GETCWD => Some("getcwd"),
        CHDIR => Some("chdir"),
        UMASK => Some("umask"),
        GETRLIMIT => Some("getrlimit"),
        SYSINFO => Some("sysinfo"),
        GETUID => Some("getuid"),
        GETGID => Some("getgid"),
        SETUID => Some("setuid"),
        SETGID => Some("setgid"),
        GETEUID => Some("geteuid"),
        GETEGID => Some("getegid"),
        SETPGID => Some("setpgid"),
        GETPPID => Some("getppid"),
        GETPGRP => Some("getpgrp"),
        GETRESUID => Some("getresuid"),
        GETRESGID => Some("getresgid"),
        GETPGID => Some("getpgid"),
        GETSID => Some("getsid"),
        SIGALTSTACK => Some("sigaltstack"),
        SETRLIMIT => Some("setrlimit"),
        GETTID => Some("gettid"),
        SET_TID_ADDRESS => Some("set_tid_address"),
        CLOCK_GETTIME => Some("clock_gettime"),
        OPENAT => Some("openat"),
        FSTATAT => Some("fstatat"),
        FACCESSAT => Some("faccessat"),
        ACCEPT4 => Some("accept4"),
        DUP3 => Some("dup3"),
        PIPE2 => Some("pipe2"),
        PRLIMIT64 => Some("prlimit64"),
        _ => None,
    }
}
